openapi: 3.0.0
info:
  title: Tweets service API
  description: Tweets API
  version: 0.1.9
servers:
  - url: /api

paths:
  /tweets/search:
    post:
      tags:
        - Tweets
      summary: Get Tweets list or filter it
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchResourceRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: './schemas/tweets.yaml#/TweetsResponse'
        '401':
          description: Unauthorized
  /tweets:
    post:
      tags:
        - Tweets
      summary: Create Tweet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/tweets.yaml#/TweetCreateRequest'
      responses:
        '200':
          description: Tweet Created
          content:
            application/json:
              schema:
                $ref: './schemas/tweets.yaml#/TweetResponse'
        '400':
          description: Bad request
        500:
          description: Server error
  /tweets/{id}:
    get:
      tags:
        - Tweets
      summary: Get Tweet by id
      description: Get Tweet by id
      parameters:
        - $ref: '#/components/parameters/PathId'
        - $ref: '#/components/parameters/QueryInclude'
      responses:
        '200':
          description: Tweet Created
          content:
            application/json:
              schema:
                $ref: './schemas/tweets.yaml#/TweetResponse'
        '400':
          description: Bad request
        500:
          description: Server error
    delete:
      tags:
        - Tweets
      summary: Delete Tweet by id
      description: Delete Tweet by id
      parameters:
        - $ref: '#/components/parameters/PathId'
      responses:
        '200':
          description: Tweet Deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptyResource'
        '400':
          description: Bad request
        500:
          description: Server error
    patch:
      tags:
        - Tweets
      summary: Update Tweet by id
      description: Update Tweet by id
      parameters:
        - $ref: '#/components/parameters/PathId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './schemas/tweets.yaml#/TweetUpdateRequest'
      responses:
        '200':
          description: Tweet Updated
          content:
            application/json:
              schema:
                $ref: './schemas/tweets.yaml#/TweetResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    PathId:
      in: path
      name: id
      required: true
      schema:
        type: integer
        minimum: 1
      description: Числовой id
      example: 1
    QueryInclude:
      in: query
      name: include
      required: false
      description: Relationships
      schema:
        type: string
  schemas:
    EmptyResource:
      type: object
      properties:
        data:
          type: object
          nullable: true
          example: null
    SearchResourceRequest:
      type: object
      properties:
        filter:
          type: object
          properties:
            name:
              type: string
        include:
          type: array
        sort:
          type: array
