openapi: 3.0.0
info:
  title: Skeleton API
  description: Skeleton API for Megafon Tajikistan
  version: 0.1.9
servers:
  - url: /api

paths:
  /users:
    get:
      summary: Returns a list of users.
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    PathId:
      in: path
      name: id
      required: true
      schema:
        type: integer
        minimum: 1
      description: Числовой id
      example: 1
    QueryInclude:
      in: query
      name: include
      required: false
      description: Relationships
      schema:
        type: string
  schemas:
    EmptyResource:
      type: object
      properties:
        data:
          type: object
          nullable: true
          example: null
